name: build

on:
  push:
  pull_request:
  release:
    types: [published]
permissions:
  contents: write
  id-token: write
jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: build
        id: build
        shell: bash
        run: |
          export VERSION=0.0.1
          [ "${GITHUB_REF_TYPE}" == "tag" ] && VERSION="${GITHUB_REF_NAME}"
          ./build-windows.sh
          installer_path="$(./package-windows.sh)"
          echo "installer_path=${installer_path}" >> "${GITHUB_OUTPUT}"
          echo "installer_name=${installer_path##*/}" >> "${GITHUB_OUTPUT}"

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ${{ steps.build.outputs.installer_name}}
          path: ${{ steps.build.outputs.installer_path}}
          if-no-files-found: error

      - uses: sigstore/cosign-installer@d7543c93d881b35a8faa02e8e3605f69b7a1ce62 # v3.10.0
        if: startsWith(github.ref, 'refs/tags/')

      - name: sign installer
        id: sign
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cosign sign-blob "${{ steps.build.outputs.installer_path }}" --yes --bundle cosign.bundle
          echo "cosign_bundle=cosign.bundle" >> "${GITHUB_OUTPUT}"

      - name: release
        uses: softprops/action-gh-release@aec2ec56f94eb8180ceec724245f64ef008b89f5 # v2.4.0
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          files: |
            ${{ steps.build.outputs.installer_path}}
            ${{ steps.sign.outputs.cosign_bundle}}
